#command: bundle exec rails db:chatwoot_prepare


services:
  chatwoot-rails:
    image: chatwoot/chatwoot:v4.0.3

    environment:

      #configuracao SMTP
      MAILER_SENDER_EMAIL: ${MAILER_SENDER_EMAIL}
      SMTP_DOMAIN: ${SMTP_DOMAIN}
      SMTP_ADDRESS: ${SMTP_ADDRESS}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_AUTHENTICATION: login
      SMTP_ENABLE_STARTTLS_AUTO: "true"
      SMTP_OPENSSL_VERIFY_MODE: "peer"
      MAILER_INBOUND_EMAIL_DOMAIN: ${MAILER_INBOUND_EMAIL_DOMAIN}
      
      RAILS_ENV: "production"
      NODE_ENV: "production"
      INSTALLATION_ENV: "docker"

      SECRET_KEY_BASE: ${CHATWOOT_SECRET_KEY_BASE}
      FRONTEND_URL: ${CHATWOOT_FRONTEND_URL}
      ENABLE_ACCOUNT_SIGNUP: "false"

      # Banco e Redis (caso estejam em outro compose ou serviços)
      POSTGRES_HOST: "postgres"
      POSTGRES_USERNAME: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DB_CHATWOOT}
      REDIS_URL: "redis://redis:6379"
      #ACTIVE_STORAGE_SERVICE: local

      # Configurações S3/MinIO
      ACTIVE_STORAGE_SERVICE: "s3_compatible"
      STORAGE_BUCKET_NAME: ${CHATWOOT_STORAGE_BUCKET}
      STORAGE_ACCESS_KEY_ID: ${CHATWOOT_ACCESS_KEY_ID}
      STORAGE_SECRET_ACCESS_KEY: ${CHATWOOT_SECRET_ACCESS_KEY}
      STORAGE_REGION: ${CHATWOOT_STORAGE_REGION}
      STORAGE_ENDPOINT: ${CHATWOOT_STORAGE_ENDPOINT}
      STORAGE_FORCE_PATH_STYLE: "true"
      AWS_REGION: ${CHATWOOT_STORAGE_REGION}


      # Exemplo de chave OpenAI (opcional)
      #OPENAI_COMPLETIONS_ENABLED: "true"
      #OPENAI_API_KEY: ""

      # Logs
      RAILS_LOG_TO_STDOUT: "true"
      LOG_LEVEL: "info"

    networks:
      - app_network
    ports:
      - "3000:3000"
    volumes:
      - chatwoot_data:/app/storage
    restart: always
    entrypoint: docker/entrypoints/rails.sh
    command: ["bundle", "exec", "rails", "s", "-p", "3000", "-b", "0.0.0.0"]

  chatwoot-sidekiq:
    image: chatwoot/chatwoot:v4.0.3

    environment:
      #configuracao SMTP
      MAILER_SENDER_EMAIL: ${MAILER_SENDER_EMAIL}
      SMTP_DOMAIN: ${SMTP_DOMAIN}
      SMTP_ADDRESS: ${SMTP_ADDRESS}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_AUTHENTICATION: login
      SMTP_ENABLE_STARTTLS_AUTO: "true"
      SMTP_OPENSSL_VERIFY_MODE: "peer"
      MAILER_INBOUND_EMAIL_DOMAIN: ${MAILER_INBOUND_EMAIL_DOMAIN}
      
      RAILS_ENV: "production"
      NODE_ENV: "production"
      INSTALLATION_ENV: "docker"

      SECRET_KEY_BASE: ${CHATWOOT_SECRET_KEY_BASE}
      FRONTEND_URL: ${CHATWOOT_FRONTEND_URL}
      ENABLE_ACCOUNT_SIGNUP: "false"

      POSTGRES_HOST: "postgres"
      POSTGRES_USERNAME: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DB_CHATWOOT}
      REDIS_URL: "redis://redis:6379"
      #ACTIVE_STORAGE_SERVICE: local
      #Mesmas configs de MinIO/S3
      ACTIVE_STORAGE_SERVICE: "s3_compatible"
      STORAGE_BUCKET_NAME: ${CHATWOOT_STORAGE_BUCKET}
      STORAGE_ACCESS_KEY_ID: ${CHATWOOT_ACCESS_KEY_ID}
      STORAGE_SECRET_ACCESS_KEY: ${CHATWOOT_SECRET_ACCESS_KEY}
      STORAGE_REGION: ${CHATWOOT_STORAGE_REGION}
      STORAGE_ENDPOINT: ${CHATWOOT_STORAGE_ENDPOINT}
      STORAGE_FORCE_PATH_STYLE: "true"
      AWS_REGION: ${CHATWOOT_STORAGE_REGION}

      #OPENAI_COMPLETIONS_ENABLED: "true"
      #OPENAI_API_KEY: ""

      RAILS_LOG_TO_STDOUT: "true"
      LOG_LEVEL: "info"

    networks:
      - app_network
    volumes:
      - chatwoot_data:/app/storage
    restart: always
    command: ["bundle", "exec", "sidekiq", "-C", "config/sidekiq.yml"]

volumes:
  chatwoot_data:
networks:
  app_network:
    external: true
