services:
  n8n_editor:
    image: n8nio/n8n:1.122.3
    ports:
      - "5678:5678"      # Expondo a porta do editor
    volumes:
      - n8n_data:/home/node/.n8n
      - tmp_data:/home/n8n/.tmp
    networks:
      - app_network
    restart: always 
 
    environment:
      DB_TYPE: postgresdb
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_DATABASE: ${POSTGRES_DB_N8N}
      DB_POSTGRESDB_USER: ${POSTGRES_USER}
      DB_POSTGRESDB_PASSWORD: ${POSTGRES_PASSWORD}
      N8N_ENCRYPTION_KEY: ${N8N_ENCRYPTION_KEY}
      N8N_HOST: ${N8N_HOST}
      N8N_EDITOR_BASE_URL: ${N8N_EDITOR_BASE_URL}
      N8N_PROTOCOL: http
      NODE_ENV: production
      WEBHOOK_URL: ${N8N_WEBHOOK_URL}
      EXECUTIONS_MODE: queue
      QUEUE_BULL_REDIS_HOST: redis
      QUEUE_BULL_REDIS_PORT: 6379
      QUEUE_BULL_REDIS_DB: 2
      NODE_FUNCTION_ALLOW_EXTERNAL: moment
      EXECUTIONS_DATA_PRUNE: 'true'
      EXECUTIONS_DATA_MAX_AGE: 336
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: 'true'
      N8N_SECURE_COOKIE: "false"
      N8N_RUNNERS_ENABLED: "true"
      N8N_RUNNERS_MODE: internal
      OFFLOAD_MANUAL_EXECUTIONS_TO_WORKERS: "true"

      
  n8n_webhook:
    image: n8nio/n8n:1.122.3
    command: webhook
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - app_network
    restart: always 
  
    
    environment:
      DB_TYPE: postgresdb
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_DATABASE: ${POSTGRES_DB_N8N}
      DB_POSTGRESDB_USER: ${POSTGRES_USER}
      DB_POSTGRESDB_PASSWORD: ${POSTGRES_PASSWORD}
      N8N_ENCRYPTION_KEY: ${N8N_ENCRYPTION_KEY}
      N8N_HOST: ${N8N_HOST}
      N8N_EDITOR_BASE_URL: ${N8N_EDITOR_BASE_URL}
      N8N_PROTOCOL: http
      NODE_ENV: production
      WEBHOOK_URL: ${N8N_WEBHOOK_URL}
      EXECUTIONS_MODE: queue
      QUEUE_BULL_REDIS_HOST: redis
      QUEUE_BULL_REDIS_PORT: 6379
      QUEUE_BULL_REDIS_DB: 2
      NODE_FUNCTION_ALLOW_EXTERNAL: moment
      EXECUTIONS_DATA_PRUNE: 'true'
      EXECUTIONS_DATA_MAX_AGE: 336
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: 'true'
      N8N_SECURE_COOKIE: "false"  
      N8N_RUNNERS_ENABLED: "true"
      N8N_RUNNERS_MODE: internal
      OFFLOAD_MANUAL_EXECUTIONS_TO_WORKERS: "true"

  n8n_worker:
    image: n8nio/n8n:1.122.3
    command: worker --concurrency=5
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - app_network
    restart: always 
    environment:
      DB_TYPE: postgresdb
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_DATABASE: ${POSTGRES_DB_N8N}
      DB_POSTGRESDB_USER: ${POSTGRES_USER}
      DB_POSTGRESDB_PASSWORD: ${POSTGRES_PASSWORD}
      N8N_ENCRYPTION_KEY: ${N8N_ENCRYPTION_KEY}
      N8N_HOST: ${N8N_HOST}
      N8N_EDITOR_BASE_URL: ${N8N_EDITOR_BASE_URL}
      N8N_PROTOCOL: https
      NODE_ENV: production
      WEBHOOK_URL: ${N8N_WEBHOOK_URL}
      EXECUTIONS_MODE: queue
      QUEUE_BULL_REDIS_HOST: redis
      QUEUE_BULL_REDIS_PORT: 6379
      QUEUE_BULL_REDIS_DB: 2
      NODE_FUNCTION_ALLOW_EXTERNAL: moment
      EXECUTIONS_DATA_PRUNE: 'true'
      EXECUTIONS_DATA_MAX_AGE: 336
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: 'true'
      N8N_SECURE_COOKIE: "false"
      N8N_RUNNERS_ENABLED: "true"
      N8N_RUNNERS_MODE: internal
      OFFLOAD_MANUAL_EXECUTIONS_TO_WORKERS: "true"

  

volumes:
  n8n_data:
  tmp_data:

networks:
  app_network:
    external: true
